sudo: required
services:
    - docker

before_install:
    - docker build -t alexyoungz/docker-and-Kubernetes/frontend -f Dockerfile.dev .

script:
    - docker run -e CI=true alexyoungz/docker-and-Kubernetes/frontend npm run test